services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: fastapi_db
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3307:3306"  # Change the host port to 3307
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      DATABASE_URL: mysql+pymysql://username:password@db:3306/dbname
      SECRET_KEY: ${SECRET_KEY}
      REDIRECT_URI: ${REDIRECT_URI}

volumes:
  db_data:
